name: Despliegue en Producción en Raspberry Pi
on:
  push:
    branches:
      - dev  # Activar el workflow solo cuando se haga push a la rama dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Deploy to Raspberry Pi
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.RASPBERRY_PI_ADDRESS }}
        username: ${{ secrets.RASPBERRY_PI_USERNAME }}
        password: ${{ secrets.RASPBERRY_PI_SSH_PASSWORD }}
        script: |
          cd Proyectos/telegramemojicounter
          sudo git pull origin dev
          ./deploy_script.sh
